### PR TITLE
Add vs2022

### PR DESCRIPTION
**Pull request by mdavidsaver**
Add `vs2022` version, which appears in recent [Windows 11 VM images](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/).

### CODE REVIEW

**Comment by ralphlange** [comment]
Is it 2022 yet? Oh my...

For the issue of missing `_mkgmtime32` on 32bit Wine - well, removing all 32 bit builds from base strikes back, I would say.

**Comment by mdavidsaver** [comment]
I'm not in any hurry to fix 32-bit windows issues (msvc or mingw)

Which leaves `vs2017 / debug / windows-2016` failing with:

```
  c:\users\runneradmin\.cache\seq-r2-2-8\test\validate\evflag.st(132): error C2065: 's': undeclared identifier
  make[3]: *** Waiting for unfinished jobs....
  c:\users\runneradmin\.cache\seq-r2-2-8\test\validate\evflag.st(129): fatal error C1075: '{': no matching token found
```

Is this a regression?

**Comment by FreddieAkeroyd** [comment]
Is it possible to force the builds to run again, just in case it was transient? The PR does not change the code compiled, and it did work with the  vs2017 / debug / windows2016 combination before. Indeed it still works for static, static-debug and default, it is just debug that fails. The only `s` i can see is from `option +s` in the `evFlag.st`, it would be good to see what `evFlag.c` contains. I ran windows-x64-debug with vs2017 on a windows10 pc here and all worked fine, if a re-run of the ci build fails again I'll see if i can spin up a windows2016 machine on azure to test more

**Comment by FreddieAkeroyd** [comment]
The same build combination seems to have passed on appveyor, so maybe it is indeed transient?

**Comment by FreddieAkeroyd** [comment]
It looks to have passed on rerun, i'm wondering if it is similar to the issue we had with msi when it occasionally wrote incomplete db files. Maybe `snc` is also not closing its output file and so occasionally all the data does not get  flushed to disk resulting in an incomplete generated .c file and the compile failure?

**Comment by FreddieAkeroyd** [comment]
Looks like seq 2-2-8 does not close the output file but seq 2-2-9 does.

**Comment by anjohnson** [comment]
Yes, I sent Ben Franksen some changes which made snc handle build failures much better. Thus it's definitely worth upgrading to 2-2-9 if possible. From the Release Notes:

>   * snc, build rules: improve behavior when compilation fails
>      This changes snc so that it either doesn't touch the output file at all or
>      else removes it if there was an error. In addition, the build rules are
>      changed so that output files are removed before trying to create them.

**Pull request merged**
