### PR TITLE
Fix qualified GCC version builds

### PR DESCRIPTION
**Pull request by mdavidsaver**
`CMP="gcc-4.8"` isn't correctly propagating the "-4.8".  This seems to be a text handling issue which this PR addresses.  It also teaches `VV=1` to print all files modified prior to building dependencies.

However, with this change I start seeing a mysterious (to me) build failure on the `gcc-4.8/ubuntu-16.04` jobs.
This job succeeded (using the wrong gcc version) prior to this ci-scripts change.

eg. https://github.com/mdavidsaver/pvxs/runs/1850225898?check_suite_focus=true#step:6:1659

```
  make[4]: Entering directory '/home/runner/.cache/base-7.0/modules/libcom/src/O.linux-x86_64'
  make[4]: *** No rule to make target 'antelope', needed by '../../../../bin/linux-x86_64/antelope'.  Stop.
  make[4]: *** Waiting for unfinished jobs....
  make[3]: *** [install.linux-x86_64] Error 2
  make[2]: *** [src.install] Error 2
  make[1]: *** [libcom.install] Error 2
  make: *** [modules.install] Error 2
  DEBUG:__main__:EXEC DONE
  g++-4.8 -o antelope  -L/home/runner/.cache/base-7.0/lib/linux-x86_64 -Wl,-rpath,/home/runner/.cache/base-7.0/lib/linux-x86_64           -rdynamic -m64         closure.o error.o lalr.o lr0.o antelope.o mkpar.o output.o reader.o skeleton.o symtab.o verbose.o warshall.o       
  make[4]: Leaving directory '/home/runner/.cache/base-7.0/modules/libcom/src/O.linux-x86_64'
```

An earlier print shows that make 4.1 is being used.

### CODE REVIEW

**Comment by ralphlange** [comment]
That antelope thing smells like a missing dependency / parallel make issue?!

**Comment by mdavidsaver** [comment]
Smells like something anyway.  I know I've seen it before, but not recently, and never with PVXS.  Since the make version hasn't changed, the only thing I can think of is some difference in the `-MM` (dep file) output.

**Comment by ralphlange** [comment]
The extensive regular expressions were added at some point by Martin @mark0n. Did you check why he was going for those? Martin, do you remember?

**Comment by mdavidsaver** [comment]
```py
In [1]: import re

In [2]: re.sub(r'^([a-zA-Z][^-]*(-[a-zA-Z][^-]*)*)+(-[0-9.]|)$', r'\1', 'gcc-4.8')
Out[2]: 'gcc-4.8'

In [3]: re.sub(r'^([a-zA-Z][^-]*(-[a-zA-Z][^-]*)*)+(-[0-9.]|)$', r'\3', 'gcc-4.8')
Out[3]: 'gcc-4.8'
```

**Comment by ralphlange** [comment]
Cross-compiler names? It was something. Martin didn't spend an hour finding the correct expressions just to not change a string.

**Comment by mdavidsaver** [comment]
I've added test cases for gcc-4.8/4.9 which currently fail.

**Comment by mdavidsaver** [comment]
@anjohnson Any idea how switching to gcc 4.8 could cause make to error like this?

>   make[4]: *** No rule to make target 'antelope', needed by '../../../../bin/linux-x86_64/antelope'.  Stop.
...
>   g++-4.8 -o antelope  -L/home/runner/.cache/base-7.0/lib/linux-x86_64 -Wl,-rpath,/home/runner/.cache/base-7.0/lib/linux-x86_64           -rdynamic -m64         closure.o error.o lalr.o lr0.o antelope.o mkpar.o output.o reader.o skeleton.o symtab.o verbose.o warshall.o

**Comment by anjohnson** [comment]
Looking at the log from the first failing builder, antelope gets linked on line 1699 and then again on line 1790. It definitely looks like it's running the build all over again, because if you look at line 1706 it's recreating the file timerQueuePassive.d which is first created around line 962 IIRC. Could this somehow be related to the recreation of libComVersion.h on line 1703 which it first did on line 923 and installed on 1245?

I'm not aware of anything that has a dependency on the $(CC) or $(CCC), so I can't explain why switching to gcc-4.8 might cause this.

I would expect it to be doing that by setting `CMPLR_SUFFIX` in a `CONFIG_SITE.Common.<host>` file but I don't see it doing that anywhere. However it does appear to be setting CC and CCC in configure/os/CONFIG_SITE.Common.<host> which I believe is a problem though, since they get set in CONFIG.gnuCommon. This recent-ish comment in e.g. CONFIG_SITE.Common.linux-x86_64 explains:
```Makefile
# WARNING: Variables that are set in $(CONFIG)/CONFIG.gnuCommon cannot be
# overridden in this file for native builds, e.g. variables such as
#    OPT_CFLAGS_YES, WARN_CFLAGS, SHRLIB_LDFLAGS
# They must be set in CONFIG_SITE.linux-x86_64.linux-x86_64 instead.
```

I would recommend not trying to set CC and CCC (cue.py lines 893, 907), but instead set `CMPLR_SUFFIX` there instead, overriding the empty default. I don't know if this will fix this antelope build problem though.

**Comment by mdavidsaver** [comment]
> setting CC and CCC in configure/os/CONFIG_SITE.Common

Strictly speaking `CONFIG_SITE.Common.$(T_A)`.

Isn't this the accepted way to choose `clang`?

**Comment by mdavidsaver** [comment]
FYI. I've added printing of the contents of all generated/modified Makefile snippets.

eg. https://github.com/epics-base/ci-scripts/pull/58/checks?check_run_id=1850394505#step:4:254

**Comment by ralphlange** [comment]
In addition to the antelope thing:
I have the impression - looking at recent GH Actions logs - that make descends into the O.$(T_A) for every single action. Be it an include file that is being installed, a source file that is compiled, ...
See e.g. https://github.com/epics-base/epics-base/runs/1845680266?check_suite_focus=true

**Comment by mdavidsaver** [comment]
fyi. I tried `PARALLEL_MAKE=1` and see the same failure, and still see `antelope` being linked twice.

https://github.com/mdavidsaver/ci-scripts/runs/1850800019?check_suite_focus=true

**Comment by ralphlange** [comment]
But also `cd O.$T_A` for every single file.

**Comment by mdavidsaver** [comment]
I see this too, and am not sure of the significance since it also happens with the successful builds.

**Comment by ralphlange** [comment]
This didn't use to be the case. What I want to say: something in our build system is fishy.

**Comment by mdavidsaver** [comment]
No doubt.

I thought I'd try to reproduce with a local ubuntu/xenial VM, but apparently I deleted my old instance at some point.  Now the installer is [misbehaving](https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1817358).  Getting past this the installed image hangs on boot.  So much for this approach...

**Comment by anjohnson** [comment]
> But also cd O.$T_A for every single file.

This is actually an effect of the `-Otarget` flag and parallel builds. It's not actually doing a separate cd for each target, but collecting all of the output from that one build and showing the directory name it was in at the beginning and end.

**Comment by anjohnson** [comment]
You could try switching to `-Orecurse` which might make more sense for CI builds that aren't normally being watched live. Here's what the info page says:

> The 'target' and 'recurse' modes both collect the output of the
entire recipe of a target and display it uninterrupted when the recipe
completes.  The difference between them is in how recipes that contain
recursive invocations of 'make' are treated (*note Recursive Use of
'make': Recursion.).  For all recipes which have no recursive lines, the
'target' and 'recurse' modes behave identically.
>
> If the 'recurse' mode is chosen, recipes that contain recursive
'make' invocations are treated the same as other targets: the output
from the recipe, including the output from the recursive 'make', is
saved and printed after the entire recipe is complete.  This ensures
output from all the targets built by a given recursive 'make' instance
are grouped together, which may make the output easier to understand.
However it also leads to long periods of time during the build where no
output is seen, followed by large bursts of output.  If you are not
watching the build as it proceeds, but instead viewing a log of the
build after the fact, this may be the best option for you.
>
> If you are watching the output, the long gaps of quiet during the
build can be frustrating.  The 'target' output synchronization mode
detects when 'make' is going to be invoked recursively, using the
standard methods, and it will not synchronize the output of those lines.
The recursive 'make' will perform the synchronization for its targets
and the output from each will be displayed immediately when it
completes.  Be aware that output from recursive lines of the recipe are
not synchronized (for example if the recursive line prints a message
before running 'make', that message will not be synchronized).

**Comment by anjohnson** [comment]
>> setting CC and CCC in configure/os/CONFIG_SITE.Common.$(T_A)

> Isn't this the accepted way to choose clang?

Those suggestions on how to switch to clang were moved to `CONFIG_SITE.linux-x86.linux-x86` and `CONFIG_SITE.linux-x86_64.linux-x86_64` by the same commit that added the comments about variables set in `CONFIG.gnuCommon` because they don't actually work in `CONFIG_SITE.Common.$(T_A)` in Linux.

**Comment by mdavidsaver** [comment]
> I would recommend not trying to set CC and CCC (cue.py lines 893, 907), but instead set `CMPLR_SUFFIX` there instead, overriding the empty default. I don't know if this will fix this antelope build problem though.

Unfortunately this results in `/usr/bin/ar-4.8` which doesn't exist.

**Comment by mdavidsaver** [comment]
`apt-get install gcc-4.8` **Doesn't install the C++ compiler**!  sigh...

> make[4]: *** No rule to make target 'antelope', needed by '../../../../bin/linux-x86_64/antelope'. Stop.

This is apparently the error which results when `/usr/bin/gcc-4.8` exists, but `/usr/bin/g++-4.8` doesn't.  I hate makefiles!

**Comment by ralphlange** [comment]
DANG!

Note to self: antelope is the first thing in the build that needs a C++ compiler to be built.

**Comment by mdavidsaver** [comment]
The recipe for installing gcc (and g++) 4.8 is getting longer.  Is this something which cue.py should internalize?  If so, is this part of `prepare`, or some new `osprepare` command?  As I recall, some people run ci-scripts locally, and might object to attempts to `sudo apt-get ...`.

```sh
        export GCC_NAME="${{ matrix.cmp }}"
        sudo apt-get update
        sudo apt-get -y install software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get -y install g++-${GCC_NAME#gcc-}
```

**Pull request merged**
