### PR TITLE
Version 3.0 (single Python script, Windows builds on Travis)

### PR DESCRIPTION
**Pull request by ralphlange**
This is the (major) new release 3.0:

- Uses a single Python script for all builds on both Travis and AppVeyor
- Supports native Windows builds on Travis (five parallel runners and caching)
- Better interface to the test related targets of the EPICS build system.

As a side effect of streamlining the implementation, the configuration syntax changed slightly (on Travis more than on AppVeyor). Refer to the updated example configuration files for details.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
A [travis build](https://travis-ci.org/github/mdavidsaver/pvxs/builds/696641016) was successful after removing the call to non-existant `mingw --version` from the cross mingw builds.  appveyor is still queuing.

**Comment by ralphlange** [comment]
`compiler: mingw` should now be `compiler: gcc` (or leave it out completely as `gcc` is default).
Also, `STATIC = YES/NO` has become `BCFG = default/static/debug/static-debug` (similar to the `configuration:` setting on AppVeyor).

Should I still recognize the `STATIC` setting for compatibility?

**Comment by ralphlange** [comment]
Ah, and please also try adding native Windows builds.
`os: windows` with the supported `compiler:` settings: `gcc` (default) and `vs2017`.

**Comment by mdavidsaver** [comment]
I think I have a (slightly hacky) way to test python3.  see https://github.com/mdavidsaver/ci-scripts/tree/cui-3.0

This does turn up an additional failure.  I had a quick look and the code handling `--depth` and can't see immediately see a problem.

```
======================================================================

FAIL: test_Default (__main__.TestAddDependencyOptions)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "cue-test.py", line 263, in test_Default

    'Module not checked out shallow (requested: default=5)')

AssertionError: False is not true : Module not checked out shallow (requested: default=5)

======================================================================

FAIL: test_SetDepthThree (__main__.TestAddDependencyOptions)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "cue-test.py", line 279, in test_SetDepthThree

    'Module not checked out shallow (requested: default=5)')

AssertionError: False is not true : Module not checked out shallow (requested: default=5)
```

**Comment by ralphlange** [comment]
So...
@mdavidsaver: I think I have Python 3.7 under control now.

**Comment by ralphlange** [comment]
Unless someone objects, I plan to merge tomorrow.
(And let support deal with the remaining issues... ;-)

**Comment by mdavidsaver** [comment]
I almost have PVXS builds working.  My remaining issue is that `TEST=NO` doesn't seem to have an effect, which is a problem for windows (DLL) builds.

**Comment by ralphlange** [comment]
Ok, I'll take care of that before I merge.
On AppVeyor or Travis or both?

**Comment by mdavidsaver** [comment]
I noticed with travis-ci.  `TEST` doesn't appear in cue.py though, so it would be both.

**Comment by ralphlange** [comment]
Oops, so obvious. Sorry.

**Pull request merged**
