### PR TITLE
Formatfix

### PR DESCRIPTION
**Pull request by dirk-zimoch**
Fix for issue #11

### CODE REVIEW

**Comment by ralphlange** [comment]
Thanks a lot!
Duh - I remember I had those fixes in ... must have dropped them in one of my commit rearranging efforts.

**Comment by dirk-zimoch** [comment]
I just noticed that I missed the error message in utils.sh. Lines 43, 80, 150, 194. They need -e as well.

**Comment by dirk-zimoch** [comment]
What about a function ?
```
die() {
  echo -e "${ANSI_RED}$1${ANSI_RESET}"
  [ "$UTILS_UNITTEST" ] || exit 1
}
```

**Comment by ralphlange** [comment]
Looks good. Isn't that how it's done?
(Another change that I did and lost during my reorganization?)

**Comment by ralphlange** [comment]
Oh, in the other script. I see.
Yes, that's a good idea! Happy to merge more commits to your branch if you have time to work on this. Otherwise I will do these changes next week.

**Comment by dirk-zimoch** [comment]
See merge request #13.

**Pull request merged**
