### PR TITLE
Rebuild dependent module

### PR DESCRIPTION
**Pull request by tboegi**

### CODE REVIEW

**Comment by ralphlange** [comment]
The commits seem to be targeting two different things.

Re: cachedir
I don't see how renaming the directory would change anything.

Re: dependency chain
I think this is overly complicated. As the dependencies are always built in the order configured in MODULE, it is enough to add all entries following an updated dependency to the build list.

**Comment by tboegi** [comment]
Thanks for the review.

Re: cachedir
...renaming the directory : It helps me to test things locally, before starting the "push and wait for minutes" workflow.

Re: dependency chain
Question to the EPICS Makefile system experts,
How do I "update dependency" for a Module ? 
If someone could give me a hint, I could work on this.

**Comment by ralphlange** [comment]
Re: cachedir
... how does a rename help testing? I am always testing locally and simply don't see how that would help.

Re: dependency chain
I don't understand your question. As I wrote above, the dependency modules are compiled in the order they appear in the MODULES setting. Compiling all modules appearing after an updated module suffices.

**Comment by ralphlange** [comment]
I think I understood your first issue - ticket #22 created.

On the other part, I still have no idea what your intention for "update dependency" is.

**Comment by ralphlange** [comment]
As discussed offline - implemented a simpler approach. Let's see if this fixes the issue.

**Pull request closed without merging**
